// import Link from "next/link"

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body>
//       { /* Area Header */}
//             <header>
//                <a href={"/"}>Home</a> | 
//                <Link href={"/profil"}>Profil</Link> | 
//                 Visi | 
//                 Kontak
//             </header>
//         {children}
//         { /* Area Footer */}
//             <footer>
//                 Copyright @copy; 2024 - Udin - IF22A
//             </footer>
//       </body>
//     </html>
//   )
// }

import Link from "next/link";
import "./globals.css"
import Image from "next/image";
// import  fontAwesome
import '@fortawesome/fontawesome-svg-core/styles.css'

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: 
  { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {/* {Area Header} */}
        <header>
          {/* {Area Banner} */}
          {/* <img src={"../images/logo.png"} alt="Error" /> */}
          <Image src={"/images/logo.png"} alt="Error" width={320} height={60}></Image>

          {/* {Area Menu} */}
          <nav className="mt-5 mb-5 flex justify-center text-center">
            <Link href={"/"} className="bg-red-400 hover:bg-red-500 text-gray-100 rounded-full px-5 py-2.5 mr-2 w-52">
              Data Mahasiswa
            </Link>
            <Link href={"/"} className="bg-red-400 hover:bg-red-500 text-gray-100 rounded-full px-5 py-2.5 ml-2 w-52">
              Log Data Mahasiswa
            </Link>
          </nav>
        </header>

        {/* {Area Content} */}
        
        {children}

         {/* area footer */}
         <footer className="flex justify-center text-center bg-color1 text-color3-satu py-15px">
            Copyright &copy; 2024 - Faiz Akbar Putra Wardani
         </footer>
      </body>
    </html>
  );
}

